### ISSUE TITLE
Double item with first outline

### ISSUE THREAD

**Issue by ChrisForsythe** [vincode-io/Zavala#101]
When creating the first outline in the ios app, I generated a title called "Testing" and added a tag called "Test"

Then I added an item to the outline called "Hey jude" which was autocorrected to "Hey Jude".

It then created two items called "Hey Jude"

I cannot reproduce this on subsequent item creations or in subsequent outlines/collections.

**Comment by vincode-io** [comment]
I've never been able to recreate this. I think I'm going to chalk it up to early release glitches and address it if we ever see it again.
