### ISSUE TITLE
Collapse from subelements

### ISSUE THREAD

**Issue by FlowBo** [vincode-io/Zavala#107]
Hej,
Great work.
It would be very nice if collapse worked from sub elements. eg:

- Outline 1 
  - Element 1
  - Element 2 **<- Cursor here**  
  - …

- Outline 2

Press Collapse result:

- Outline 1 **<- Folded** 
- Outline 2

Best 
Florian

**Comment by vincode-io** [comment]
I've added the ability to collapse the root row when in a child row. This will be in the upcoming 1.1 release.

**Comment by FlowBo** [comment]
Great! Thanks
