### ISSUE TITLE
Failing to load on MacOS

### ISSUE THREAD

**Issue by philiprenich** [vincode-io/Zavala#110]
Starting last night Zavala crashed on me and has failed to load. I have a mid-2014 Macbook Pro at work, and a 2017 Macbook Pro at home. Both running Big Sur 10.4.

Yesterday I created a new outline on my work. When I got home Zavala was open, but crashed as I tried to use it. Upon reload it was showing the new outline with no title. I may have forgotten to title it while at work, not sure. I added a title and forgot about things.

Today, when I got in to the office, Zavala was non-responsive and I had to force quit. It now will not load. 

It feels like maybe something has corrupted with iCloud sync? On my phone, everything is showing and loading fine though.

Are there logs somewhere I can look through & post up here for debug? 

I haven't tried a reboot yet as I'm in the middle of work and don't need the app atm, but can report back when I do.

**Comment by vincode-io** [comment]
I have a known issue that can cause Zavala to not load until a reboot happens. Alternately, you can force quit the `filecoordinationd` process if you don't want to reboot.

I think I have a solution and plan to release an update in the next couple days that resolves it.

**Comment by philiprenich** [comment]
Killing the process did the trick, thanks!

**Comment by vincode-io** [comment]
This should be fixed in Zavala 1.0.2.
