### ISSUE TITLE
Move local outlines to iCloud

### ISSUE THREAD

**Issue by JaWeilBaum** [vincode-io/Zavala#111]
Since iCloud was not activated at first, I created some outlines locally of my mac, which I would love to export/make available to iCloud so I can view and edit them on my iOS/iPadOS devices.

**Comment by vincode-io** [comment]
You can drag your outlines from your local account to your iCloud account.

**Comment by JaWeilBaum** [comment]
Sorry for opening this issue - I was constantly stuck on the `Open quickly` window, where this drag and drop feature is not working :(

**Comment by vincode-io** [comment]
No problem. 

In the upcoming 1.1 version, I'm adding the option to always open the main window instead of the Open Quickly window.

**Comment by JaWeilBaum** [comment]
Looking forward to this - Thanks for developing this tool 🙌
