### ISSUE TITLE
Row level tags

### ISSUE THREAD

**Issue by vincode-io** [vincode-io/Zavala#122]
At this time [tags are only available at the outline level](https://github.com/vincode-io/Zavala/discussions/56#discussioncomment-1136747).

I am curious if there are more people who want tags at line level. I think that tags at line level are very useful.

It would be great to have the option to choose between searching for a tag in one outline, or in all outlines. (Maybe how Dynalist handles tags?)

_Originally posted by @latvia234 in https://github.com/vincode-io/Zavala/discussions/114_

**Comment by vincode-io** [comment]
One of the many use cases of tags on line level: https://youtu.be/wd8aRoTULoU?t=104

**Comment by pooldoo** [comment]
Line level tags are not important to me.

**Comment by vincode-io** [comment]
This issue has been superseded by #134.
