### ISSUE TITLE
iOS app does support user installed fonts

### ISSUE THREAD

**Issue by KizzyCode** [vincode-io/Zavala#125]
If I install custom fonts via an iOS configuration profile, those are not shown in Zavala on iOS. Other apps like Pages can use those fonts, so I assume they are installed correctly.

Please let me know if you need additional information 😅

**Comment by vincode-io** [comment]
I've got this fixed and it will be in the 1.1.2 release which is due this week.

**Comment by KizzyCode** [comment]
Very cool, thank you!
