### ISSUE TITLE
Dictation canceled

### ISSUE THREAD

**Issue by Manumit32** [vincode-io/Zavala#138]
On iPhone/iOS (15.1), when entering data in dictation mode, as soon as the cursor wraps to a new line, dictation mode is cancelled.  You then have to restart dictation for every new line.

**Comment by vincode-io** [comment]
I dug into this and it doesn't look like there is a way to preserve the keyboard dictation state between different text fields. I'll file a bug report with Apple about this. Hopefully they will add something in a future release.

**Comment by Manumit32** [comment]
Hello Maurice,

I thought I would reply to sort of tweak yours and perhaps my understanding of the issue. My concern is not with the dictation remaining active as I go to a new item rather that dictation seems to end as soon as a sentence automatically wraps to the next line.

In the case of an iPhone this might be after only four words or a few more words, in the case of my iPad. 

I don’t believe this is an apple iOS related issue as I do not have this problem with any other application including email, text messages, notes, messenger, etc.

Regards,
Rachel.

**Comment by vincode-io** [comment]
Sorry for misunderstanding you. That is definitely a bug in the 1.x series and if you are running the 2.0 beta using iOS 14. If you use iOS 15 and use the new Beta 2.0 version this no longer happens.

Here is a blog post if you want to try out the new Beta 2.0 version. It would be helpful if you could verify for me that this is no longer an issue when using iOS 15 and on Beta 2.0.

https://zavala.vincode.io/2021/12/09/2.0_Beta_1.html

**Comment by Manumit32** [comment]
That worked. Thank you. 

Rachel.
