### ISSUE TITLE
Emoji + SF Pro = cropped line items

### ISSUE THREAD

**Issue by dansherman** [vincode-io/Zavala#140]
I noticed a little bug when I used emoji in outline items with the SF Pro font. The bottom portion of the line is cropped off. It looks like a line-spacing/line-height issue.

Everything seems to work just fine if I leave the font set to the default Helvetica Neue.

It's a pretty minor issue but I thought you'd like to know about it.

<img width="334" alt="Helvetica - full emoji" src="https://user-images.githubusercontent.com/1310290/152837298-577a2b05-a81b-46be-a9ab-ac000265a71c.png">
<img width="505" alt="SF Pro - cropped emoji" src="https://user-images.githubusercontent.com/1310290/152837300-704cd95b-6a73-4bdc-94b1-2ebc82ecdef8.png">

**Comment by vincode-io** [comment]
Are you using version 2.0.x on macOS? Could you let me know which version of macOS you are using?

**Comment by dansherman** [comment]
Sure thing: Version 2.0.3 (46)
(Just updated today)

**Comment by vincode-io** [comment]
Are you on Big Sur or Monterey?

**Comment by dansherman** [comment]
Monterey 12.2

**Comment by vincode-io** [comment]
I'm having a devil of a time recreating this. You were using SF Pro for the font. How many points was it? Are you on a standard or Retina display? Do you have any accessibility options turned on?

Thanks for your help with this.

**Comment by dansherman** [comment]
I spent a few minutes this morning trying to re-create it myself but was unable to get it to crop like that again. I'll keep poking at it and let you know if I see it again. 

I'm using a M1 MacBook Air plugged into an LG Ultrafine 5K. I didn't check how it displayed on the laptop screen, only on the LG monitor. I'm not using any accessibility options.

**Comment by vincode-io** [comment]
I'm not ready to give up on this one just yet. We have a screenshot that shows the bug, so we know it is real.

The real challenge now will be to figure out the right sequence of events so that it can be debugged and verified as fixed.

**Comment by vincode-io** [comment]
I'm going to close this since no one can make it happen reliably. We can reopen if necessary later.
