### ISSUE TITLE
Keyboard Shortcut for Completing Row Not Working

### ISSUE THREAD

**Issue by alecbramham** [vincode-io/Zavala#141]
iPad Pro 2020 with Magic Keyboard, iOS 15.2.1, Zavala 2.0.3

In the keyboard shortcut menu (hold cmd) there is a shortcut for completing a row in the outline (cmd + return). Nothing happens after pressing the listed combination while either editing or selecting the row. 

The return key works for “Add Row Below”.
If you tap on the shortcut inside the hold cmd menu, the row does get completed. (row completion does work through the right click/tap & hold menu)

**Comment by vincode-io** [comment]
Thanks for the bug report. I have this fixed. Look for this to be corrected in Zavala 2.0.4 which I will try to get out this week.
