### ISSUE TITLE
Word count

### ISSUE THREAD

**Issue by davidrsim-p** [vincode-io/Zavala#143]
Amazing outliner! Thank you. 

Would it be possible to have a word count for the whole outline and for the current row (and all child rows)? I'm often writing to a rough target number of words and it would be helpful to know roughly where I'm at without having to export to another app.

**Comment by davidrsim-p** [comment]
Thanks for the quick reply. 

I don't think the count has to be permanently on screen, and that wouldn't work except for the overall document rows - as you move to child rows you'd lose the count overall of the 'section' you're in. 

My thought would be simply adding a word count option to the right click menu for a row. The display could be similar to Ulysses (attached) - showing the number of words and characters for the current row and its children and for the document as a whole. 

![image](https://user-images.githubusercontent.com/86412777/153017878-374532f9-b444-43d1-8ba0-7cbad7d56ed6.png)

**Comment by vincode-io** [comment]
What I'm thinking of for a design here is that the outline total number of words would be available in the current Get Info panel for the outline. 

I'd also add a Get Info for each row that could be accessed using the row context menu. The Get Info panel for the row would include other row data like created timestamp, updated timestamp, completed timestamp, etc...

This would be done as part of the 3.0 release.
