### ISSUE TITLE
Feature idea: Add an option to set the width of the Outline Editor.

### ISSUE THREAD

**Issue by vincode-io** [vincode-io/Zavala#145]
Feature idea: Add an option to set the width of the Outline Editor.

Rationale: I often write paragraph-length topics and notes in my outlines. The view can get too wide to be readable on the desktop app, especially when working on a single document on its own window in full screen mode on a widescreen monitor.

Implementation possibilities: On macOS, the option could be added as a menu bar menu that would allow the user to choose between fit-to-window (the current configuration of the Outline Editor) and narrow (which would set a readable maximum limit the width of the Outline Editor). The option could also be added to the app preferences as a text field that would allow the user to input a maximum width (perhaps in pixels) for the Outline Editor.

PS: I love this app! Thank you for developing it! I've long been looking for a simple outliner app. (Opal used to be my preferred outliner, but it's no longer being actively developed.) John Gruber's original tweet immediately resonated with me when I saw it on my feed. I'm so glad you took action!

_Originally posted by @ba-sicheng in https://github.com/vincode-io/Zavala/discussions/144_

**Comment by rcastro0** [comment]
I second that -- I would like to have the option to make the main outline windows narrow, as sometimes I would put it on the side of the screen while a browser windows, Excel windows or something else would take most of the screen.

Currently I can resize the window to make it narrower, but only up to a certain point (about 40% of the MacBook Air screen width). After that the text in the outline is no longer responsive and get cropped.

So, I vote for letting the window be narrow.

**Comment by vincode-io** [comment]
@rcastro0 This feature isn't about the main outline window. It is about the text within a window. Some people like to run with a maximized window and super long text lines become difficult to read.

The reason that we can't completely scrunch down the main window to something super small is due to a bug in macOS. It can cause the app to crash. The only way I can prevent it is to restrict the minimum width.

I would recommend that you use individual outline windows when you want to use Zavala side-by-side with another app. You can open them by double clicking the outline in the document list (the middle pane on the main window).
