### ISSUE TITLE
Zavala macOS crashing on sync when editing documents via iCloud

### ISSUE THREAD

**Issue by brehaut** [vincode-io/Zavala#146]
I’ve experienced a crash several times now on the mac client when editing a document synced via iCloud to the iOS client. This only happens when Zavala has the same document open on macOS as is being edited on iOS (or presumably any other iCloud synced client).

### Steps to reproduce

1. Create a new iCloud synced document ("Sync crash") on macOS 
2. Add a couple of nodes
3. Open zavala on second device, wait for the new "Sync crash" document to sync, and then open it
4. With "Sync crash" still the active document on macOS, add or edit a node on the second device.
5. Wait for sync.

Note: If the "Sync crash" is not the active document on the mac client, then no crash occurs.

I can provide a stack trace etc if required

**Comment by vincode-io** [comment]
Thanks for the bug report. I must have broken this somehow in 2.0. I should be able to get this fixed in the next bug fix release.

**Comment by vincode-io** [comment]
@brehaut I'm not able to recreate this. Could you please attach a crashlog if you can still find one? It might help me figure out how to track this bug down.

**Comment by brehaut** [comment]
[zavala-icloud-sync-crash.txt](https://github.com/vincode-io/Zavala/files/8112630/zavala-icloud-sync-crash.txt)

Sure thing, let me know if you need anything else

**Comment by vincode-io** [comment]
This has been fixed and is coming in the 2.0.6 release.
