### ISSUE TITLE
FEATURE REQUEST: Better support for paste of Markdown content in text from clipboard

### ISSUE THREAD

**Issue by ChristopherA** [vincode-io/Zavala#147]
### What happened?

I paste some markdown body text, followed by lists of links. Some links are nested lists. The result should be a 3 level list, the body, the first list, and the 2nd list.

Instead, the entire clipboard become a single entry line in Zavala.

### Reproduce the Bug

original paste:
```
Outliners [2022-02-21]
- [Tangent Notes – Roadmap](http://tangentnotes.com/Roadmap)
- [Logseq: A privacy-first, open-source knowledge base](https://logseq.com/)
- [vincode-io/Zavala: A good, simple outliner for macOS, iPadOS, and iOS.](https://github.com/vincode-io/Zavala)
  - [Features - Zavala](https://zavala.vincode.io/features/)
- [Drummer: Electric Drummer](http://docserver.scripting.com/drummer/electricDrummer.opml)
```
<img width="511" alt="Markown Paste in Zavala" src="https://user-images.githubusercontent.com/69103/155027174-3377a223-f1ff-47f7-8046-bddbc80c4e2b.png">

### Expected Behavior

A) body markdown paragraphs should be new entries at same level as paste point.

B) list markdown elements should be indented.

C) indented lists inside of lists should be indented +1  more

D) Any included marked links should be converted to links.

(the following is from LogSeq, after slight reformatting):

<img width="520" alt="Expected Markdown Paste into Logseq" src="https://user-images.githubusercontent.com/69103/155019425-755bc0ec-7112-48b0-8ae4-02fba48fc3c4.png">

### Screenshots

See above.

### Desktop Platform Information

macOS Monterey 12.1 on MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)

Zavala Version 2.0.5 (48)

### Mobile Platform Information

(did not test this on iOS)

### Additional Context

Original thread on Twitter: https://twitter.com/ChristopherA/status/1495839574588895235

Logseq comes closest in supporting this: 

* https://github.com/logseq/logseq/issues/4333

Electric Drummer supported the indentation, but not the conversion of links.  They closed this issue, said that you have to import markdown from a file:

https://github.com/scripting/drummerSupport/issues/155

**Comment by vincode-io** [comment]
Thanks for the feature request. 

Importing Markdown is super hard to get right which is why it isn't currently implemented. Apple's new open source Markdown parser looks promising though. In the 3.0 release cycle, I'm going to try implement Markdown importing, but no guarantees that I'll be successful.

**Comment by vincode-io** [comment]
This looks to be the same as #189. When this issue gets resolved, we should be able to drag a hierarchy of rows from OmniOutliner into Zavala and get the result that is expected.

**Comment by vincode-io** [comment]
@ChristopherA Pasting Markdown unordered lists will be supported in the upcoming Zavala 2.7 release.
