### ISSUE TITLE
Can't disable "check spelling", auto-correction, etc. on Mac

### ISSUE THREAD

**Issue by jeffmann** [vincode-io/Zavala#150]
Thanks for this app, I'm trying it out for the first time, using macOS 12.3.

I can't seem to turn off auto-correction (where the little box with suggestions pops up), spell checking (red underlines) and related things.

I expected there to be settings in Preferences for Auto-Correction, like there is in Pages, Numbers, etc., with persistent options like "Correct spelling automatically", "Capitalize words automatically", "Use smart quotes and dashes", "Symbol and text substitution", etc.

I did find options in the menu "Edit > Spelling and Grammar" for "Check Spelling While Typing" and "Correct Spelling Automatically". I expected these to persist. However, if I uncheck these, they only stay unchecked and inactive until I press Enter and start a new line, or click to move the cursor to a different line, then they're checked and active again.

As a workaround, I used:
```
defaults write io.vincode.Zavala NSAutomaticSpellingCorrectionEnabled -bool false
```

to disable auto-correction, but I can't find a way to disable the spell checking. Neither of these work:
```
defaults write io.vincode.Zavala NSAllowContinuousSpellChecking -bool false
defaults write io.vincode.Zavala CheckSpellingWhileTyping -bool false
```

**Comment by vincode-io** [comment]
This is a good request. I'll include it in a future release.
