### ISSUE TITLE
Issues with embedded line breaks

### ISSUE THREAD

**Issue by jeffmann** [vincode-io/Zavala#151]
I found that I can use option-enter to create line breaks or newlines inside of a row, in other words, to have multi-line rows, which is very useful - is this documented somewhere? I can also paste text with multiple lines, like from an e-mail, into a single row. When these are exported to OPML by Zavala, they have literal newlines in the OPML.

I expected that when I re-import the OPML, the outline would look the same, and the multi-line rows would be preserved. But actually, the line breaks are lost, and the text becomes all one line.

Several major outliners that support embedded line breaks escape them in their exported OPML. For example, Dynalist uses `&#xA;` (same as `&#10;`). And, in fact, Zavala correctly imports OPML from Dynalist and preserves the multi-line text, even though it doesn't correctly import its own OPML. On the other hand, some outliners, like Circus Ponies Notebook, do export literal newlines in the OPML like Zavala currently does. It would be good to support importing that too.

I would suggest that Zavala should escape newlines when exporting OPML, for compatibility with most other contemporary outliners that support embedded line breaks. It should handle import of both literal and escaped newlines in OPML, for compatibility with some other outliners, and with its own OPML exported previously.

You can find some more information about the subject at: https://forum.legendapp.com/d/152-support-embedded-line-breaks

**Comment by vincode-io** [comment]
Thanks for the insight on on this. Importing and exporting newlines isn't something that's come up on my radar before. I appreciate you sharing your thoughts and research on this.

It all looks like it makes sense to me. I'll try to include this in a future release.

**Comment by vincode-io** [comment]
This is fixed per your suggestions and will be in the next release.
