### ISSUE TITLE
Adjustable Line Spacing

### ISSUE THREAD

**Issue by vincode-io** [vincode-io/Zavala#153]

**Comment by rcastro0** [comment]
Yes, I vote for that. I was using the trial version for Omni Outliner when it expired and, before buying Essentials, I thought I might want to check other options. I just found Zavala and I quite like its simple and clean approach. However I think the white padding around lines makes it not so much efficient in terms of vertical space usage.

So... like you do for font size, please make an option in preferences for line spacing... (I hope this is not hard to implement).

Thanks

**Comment by vincode-io** [comment]
Duplicate of #192.
