### ISSUE TITLE
Crashing bug (MacOS): Splitting lines after pasting text

### ISSUE THREAD

**Issue by robertsalsbury** [vincode-io/Zavala#155]
Hi - 

with release 2.0.7, on Monterey 12.3, intel i9 (MBP 2019), if you make a new document, title it, then paste into the first line (cursor active, not inactive), the full text from the pasteboard will be entered as a single outline item. 

Attempting to then split that item with keyboard command option-shift-return will crash the app. I tried it placing the cursor at the end of the first line of text, and at various places farther down within the text. 

Pasting with the cursor inactive behaves well, splitting each line of the clipboard to a new outline line-item. 

Not sure if this matters, but I am pasting from NotePlan. The text I'm pasting follows my sig here.

-Robert

```
# Dyja,Thomas-New York, New York, New York  

## Info  
 - Author:  Thomas Dyja
 - Pub Year:  2021
 - Format: paperback

## Notes  


## Characters  

## Outline  
- I Renaissance
	- 1 ‘I Love NY Day’
	- 2 Something it hadn’t been
		- ‘the organization man’ 
---
--built with Shortcuts on Apr 5, 2022 at 11:08 AM--

```

**Comment by vincode-io** [comment]
This has been fixed and will be in the upcoming 2.0.8 release.
