### ISSUE TITLE
Bug: Pasting (iOS) can reverse order of text

### ISSUE THREAD

**Issue by robertsalsbury** [vincode-io/Zavala#156]
On build 2.0.7, on both iPhone and iPad, pasting text when the cursor is NOT active will reverse the order of the pasted text, line by line. 

If you make a note in Apple Notes, with any title, and then type text
```
1
2
3
4
5
```
select that text, and copy it. 

Then open Zavala, make a new outline, type something for the title, then tap into the outline area to create a single empty item, and swipe down to dismiss the keyboard and make the cursor inactive. 
Now tap-and-hold on screen to active the context menu, and select "paste".
The text will paste as follows:
```

5
4
3
2
1
```

**Comment by vincode-io** [comment]
This has been fixed and this will be in the 2.0.8 release.

Thanks for the bug reports @robertsalsbury!
