### ISSUE TITLE
Cloudkit Syncing Error

### ISSUE THREAD

**Issue by JaapvanderVeen** [vincode-io/Zavala#164]
Error message:
(https://user-images.githubusercontent.com/60818500/170727861-00c84759-6795-4406-9b80-8fa927153efd.png)

Internet connection is definiteley not offine

**Comment by vincode-io** [comment]
This error is thrown by Apple's CloudKit framework when it can't connect to iCloud. There was probably a disruption in your internet service at the time you received this error. 

Are you still getting the error?

**Comment by JaapvanderVeen** [comment]
Working now! Thx
