### ISSUE TITLE
MacOS Keyboard Shortcuts Do Not Work

### ISSUE THREAD

**Issue by charlieharrysmith** [vincode-io/Zavala#165]
Loving Zavala so far, it's fantastic to be able to jot down outlines across my devices. Thank you!

One issue on Mac I've found is that the `Move Left/Right/Up/Down` shortcuts simply do not work. Unless I'm missing something, `Shift + CMD + Arrow Key` fails to return the expcted behaviour—nothing happens.

Any ideas what I'm doing wrong here?

**Comment by vincode-io** [comment]
Is it possible that you have those keys remapped? Are you using any software that may be intercepting those keystrokes?

**Comment by vincode-io** [comment]
@charlieharrysmith The correct keyboard shortcuts don't use shift. They use control with command. `CTRL + CMD + Arrow Key`.
