### ISSUE TITLE
Add toolbar icon for Add note

### ISSUE THREAD

**Issue by SamSandq** [vincode-io/Zavala#167]
I wanted to add this to the toolbar as I use it a lot, and noticed that it wasn't possible. Please add this option.

**Comment by SamSandq** [comment]
Just to add, the same for the iPad implementation; next to the icons for adding a link and an image.

**Comment by vincode-io** [comment]
I'll consider this for inclusion in a future release.

**Comment by vincode-io** [comment]
This has been added and will be in the upcoming 2.0.9 release.
