### ISSUE TITLE
Cleanup outline by deleting unused blanks

### ISSUE THREAD

**Issue by pramjan** [vincode-io/Zavala#174]
The idea is to have a shortcut to "cleanup" the outline, by automatically deleting unused blanks, wherever they may be in the outline. Is this possible to take up as a feature request?

**Comment by vincode-io** [comment]
Do you mean empty rows or blank spaces in rows?

**Comment by vincode-io** [comment]
I'm closing this since I'm not really sure what is being requested. Will reopen with clarification.
