### ISSUE TITLE
Multi-level fonts - inconsistent refresh issue

### ISSUE THREAD

**Issue by pramjan** [vincode-io/Zavala#175]
After changing the font for a particular level (say Topic Level 2, and Topic Level 3 were added - and each have their own fonts), what happens is that the fonts don't properly refresh throughout the outline. So, the fonts change in certain parts of the outline, as expected, but remain unchanged in certain other parts of the document.

**Comment by vincode-io** [comment]
I'm having trouble recreating this. Do you have any detailed steps you can give me to recreate this? Also, which platform are you using?
