### ISSUE TITLE
Changing the color of the text

### ISSUE THREAD

**Issue by Tristram1** [vincode-io/Zavala#176]
Right-clicking selected text allows one to bring up the Fonts window... and the Colors window.  As expected, in the Fonts window it is possible to change the font of the selected text... but not the font color.  Both windows seem to encourage the selection of colors... yet selecting a different color appears to have no impact on the color of the text.  Is this the intended behavior?

**Comment by vincode-io** [comment]
Thanks for pointing this out. Zavala doesn't support colored text and probably never will. This is to make outlines work seamlessly when switching between dark and light modes.

I'll see if there is some way that I can remove these options in a future release.

**Comment by vincode-io** [comment]
The font menu will be removed in version 2.2.
