### ISSUE TITLE
Alphabetical Sort for the outline items

### ISSUE THREAD

**Issue by pramjan90** [vincode-io/Zavala#179]
I realise we have touched slightly upon sorting in #116 - but, can we have alphabetical sorting for the outline items, both:

- top level (just the highest level),
- deep sort (for all levels - recursively sort top level, second level, third level, etc - as many as times as there are levels under each item)

This would be beneficial, because many times outlines are lists of multiple levels, and sorting makes it easy to identify if a particular item exists in a list or not.

Cheers!

**Comment by vincode-io** [comment]
I'm not too keen on adding this into the application itself. Our menus are getting too crowded as it is, especially on iOS and iPadOS.

I do think it is a valid need though. Enabling this functionality by using Shortcuts would allow this to work without overcomplicating the Zavala user interface. I would need to add another Shortcut action to make this happen.

I've created #182 to track this as a future release feature.
