### ISSUE TITLE
Formatting text (italic or bold) causes immediate crash

### ISSUE THREAD

**Issue by prc1212** [vincode-io/Zavala#183]
If I try to format selected text as italic or bold I get an immediate crash. This happens on both iPadOS (15.5) and MacOS (12.4, 2015 MBP). Both using 2.0.7 build 50.

**Comment by vincode-io** [comment]
Do you have anymore details than this? You haven't given me anything to work with here.

Does it happen on all your outlines? Has it always happened? If not, so you know what could have changed?

**Comment by prc1212** [comment]
Okay, sorry about that. It's the first time I've tried Zavala so I'm not able to compare it against past behaviour.

Now that I'm trying to reproduce the problem, it's only happening in one outline, which contains text that I pasted from Drafts. If I remove the pasted line, the formatting works fine in that outline. If I replace all text from the line but don't remove the line itself then it still crashes.

However, if I paste the same text (from Drafts) into another outline, I'm not getting the same problem. So, it seems to be some path-dependent thing that I've done without realising. If I am able to isolate it, I will report back.

**Comment by vincode-io** [comment]
It is probably a layout bug that I fixed already for the 2.0.8 release. 

If you could do me a favor and save a version of the outline that causes the crash? We could then verify that 2.0.8 does fix it or if we need to more investigating. I would really appreciate it.

**Comment by prc1212** [comment]
Save it as what? OPML?

When I re-import the outline from an OPML file I no longer get the crash... :)

**Comment by vincode-io** [comment]
Can you use the Duplicate function to make a copy of it that you can keep around?

**Comment by prc1212** [comment]
Not sure what happened but the last time it crashed and restarted something must have changed and the outline in question is no longer broken. Sorry, a bit of a waste of time!

I think I will persevere with using Zavala though so will keep an eye on it.

**Comment by vincode-io** [comment]
Thanks. I'll try to get 2.0.8
Out in a couple weeks.

We can reopen this ticket if you are able to recreate it again.
