### ISSUE TITLE
Not issue - just looking for recommendation

### ISSUE THREAD

**Issue by timfea926** [vincode-io/Zavala#184]
Just wondering if you have any recommendations on how to import Apple Notes into Zavala? I don't know of any way to import Apple Notes to OPML, which seems to be the only way to do it.

**Comment by vincode-io** [comment]
Sorry, but importing from Notes isn't possible. Notes are unstructured documents and outlines are a hierarchy of rows. They don't really map. Unfortunately you will need to move your data from Notes manually and structure it how you see fit in Zavala.

I do still use Notes even though I use Zavala for almost everything. Sometimes an unstructured document is what you really need. I could be that you won't want to move everything out of Notes and into Zavala.
