### ISSUE TITLE
Respect tabs when pasting

### ISSUE THREAD

**Issue by vincode-io** [vincode-io/Zavala#189]
When pasting while not editing in a row, we should use tabs in the pasted text to understand when a row is a child row.

**Comment by vincode-io** [comment]
If this doesn't fix dragging from OmniOutliner, then create a new issue to resolve that.

**Comment by vincode-io** [comment]
Duplicate of #147.

**Comment by jsismail** [comment]
Re #242 this doesn't solve the problem.  I tested cutting and pasting Notes outlines into Zavala, one outline used tabs the other used indentation (cmd-]).  If I paste into a Zavala outline with a row selected, the Notes outline structure is not reprodued (i.e. children become siblings of their parent).  When pasting into Zavala without a row selected, it pastes into a single multi-line row with no indentation for the cmd-] indented Notes outline, and into a single multi-line row with indentation for the tabs indented Notes outline.

**Comment by jsismail** [comment]
Pasting from Zavala into Note works as expected, where tabs are used for indentation.  There is however outline chrome that gets pasted along with the outine, in the form of asterisks that I think are unnecessary (i.e. #241).

**Comment by vincode-io** [comment]
Look for this in the upcoming Zavala 2.7 release.
