### ISSUE TITLE
Bug: Layout/display issue when adding item to the bottom of long list

### ISSUE THREAD

**Issue by evangrim** [vincode-io/Zavala#193]
In a rush and haven't nailed down steps to reproduce, so just noting this apparent bug for now: it appears that when a list is long enough to have a scrollbar, and an action other than scrolling is taken that causes the view to scroll (e.g. insert an item at the bottom fo the list and enter text item at the bottom of the list, or highlight and delete an item from near the bottom of the list), then a narrow band of content from the middle of the list improperly overlays the bottom of the window.

* Resizing the window does not correct the condition, but it does change the dimension of the buggy overlay -- see screen shot 2)
* Scroll actions (mouse, keyboard, touch pad gesture) do correct the condition

Is this a perhaps virtualized list / display size calculation issue?

![image](https://user-images.githubusercontent.com/11548185/196051206-c85f16b9-bb5e-46c0-8f1b-92868e05935a.png)

![image](https://user-images.githubusercontent.com/11548185/196051425-209a1827-b3e1-4663-b1dc-7b167ddf7980.png)

**Comment by evangrim** [comment]
I suspect this is related to [194, where Open Quickly appears as tab](https://github.com/vincode-io/Zavala/issues/194), since I can't reproduce either now.

**Comment by vincode-io** [comment]
Ok. I'll close the issue. Let me know if you see it again.
