### ISSUE TITLE
MacOs change tab to Open Quickly changes window size

### ISSUE THREAD

**Issue by evangrim** [vincode-io/Zavala#194]
1.  View > Show All Tabs; select a note tab, drag the window a bit larger ![image](https://user-images.githubusercontent.com/11548185/196238510-f5908a29-01e1-4b5b-aec6-ba673c48f4d2.png)

2. Click the Open Quickly tab and the window will resize to accommodate its contents ![image](https://user-images.githubusercontent.com/11548185/196238537-9034a822-0f36-466f-86b5-7b5bf628f9f4.png)

3. Click back to original tab, and the window is still small
![image](https://user-images.githubusercontent.com/11548185/196238793-a08dc941-172b-4865-8db1-d2b78a056c43.png)

**What should happen instead?**

I should be able to size and/or arrange the window as I prefer and have it stay that size. :)

**Comment by evangrim** [comment]
<3 this app btw..

**Comment by vincode-io** [comment]
I'm not even sure how you managed to add Open Quickly as a tab. It shouldn't be possible and I can't make it happen on macOS Monterey. Open Quickly isn't supposed to be able to be resized and that might be causing the behavior you are seeing.

What version of macOS are you using? If it is Big Sur, then being able to attach Open Quickly might an operating system bug.

It also looks like you are using an old version of Zavala. You might want to upgrade and try to stay current on it. I have done a lot of bug fixes to it this year.

**Comment by evangrim** [comment]
Thanks for response. I'm on Big Sur (can't update that, I have legacy software to contend with), but Zavala is/was apparently up to date.

I haven't been able to get Open Quickly as a tab again, but if I'm able to reproduce it I'll let you know.


![image](https://user-images.githubusercontent.com/11548185/198699348-c90af401-c58b-436a-9348-bf231a109220.png)

**Comment by vincode-io** [comment]
I think you must have updated Zavala recently. Your screen shots have the 1.0 style tags at the top of the outline. That may be why you can't attach Open Quickly anymore.

It looks like this is resolved somehow, so I'm going to close this issue. If you see it again, let me know and we'll open this one again.
