### ISSUE TITLE
Return key behavior

### ISSUE THREAD

**Issue by vincode-io** [vincode-io/Zavala#2]
Hitting the return key when at the end of a line is pretty consistent across Outliners.  It creates a new entry below the previous one and moves the cursor down.

But what should the behavior be if the cursor is at the beginning of a line of text?  Should it create a new line above the current one and move the cursor there?  That is how Workflowy does it, but OmniOutliner creates a new line below.

What should happen if the cursor is in the middle of a line of text and the return key is pressed?  Workflowy splits the line and creates two separate entries from it.  OmniOutliner creates a new line below.

Right now Manhattan works like OmniOutliner, but I wonder if that is correct.  I wanted to insert a new row at the beginning of an outline, so I put my cursor in the first position and hit return expecting a new entry to be made before my insertion point.  Instead I got an entry below my insertion point.

**Comment by davidungar** [comment]
I was about to mention this same issue, then I found this entry. Where should I have looked to find the keyboard shortcuts? I suggest some way to make those more discoverable.

**Comment by davidungar** [comment]
How do I split a line on iOS?

**Comment by vincode-io** [comment]
Holding down the command key on iOS will show you all the keyboard shortcuts currently available.

If you are using a hardware keyboard, it looks like the Split Row keyboard shortcut is missing on older versions of iOS, but is there for iOS 15. I'll fix this in the next release.

There isn't currently a way to execute the Split Row command on iOS devices without a hardware keyboard. In the next release I'll add this command to the Edit menu (the one that appears above text with Cut, Paste, etc...

Thanks for being a Zavala user and thanks for the bug report.

**Comment by davidungar** [comment]
> Split Row has been added to the iOS Edit Menu in version 2.0.3. Look for it to clear App Store approval in the next couple days (if our luck holds).

Thank you!
