### ISSUE TITLE
iCloud Sync error

### ISSUE THREAD

**Issue by tech-ki** [vincode-io/Zavala#202]
<img width="680" alt="Screenshot 2023-08-18 at 2 45 39 PM" src="https://github.com/vincode-io/Zavala/assets/19785677/e5761e15-3987-4230-bb55-b6448bba5032">

Just recently today I get an error when I try to sync my outlines cross platform. I have attached an image below. It wasn't syncing so I kept dragging down the outline to sync it. Now this error pops up. When I continue typing some of it still shows on my iphone while others won't.

**Comment by vincode-io** [comment]
It is really interesting that this dialog popped up. Usually when this is happening, Apple will supply a time to wait to try again. Zavala just waits and again attempts to sync after the wait period has expired. If you saw this dialog, it means that Apple was throttling your syncing speed, but didn't provide a wait time. I've never seen that happen before.

You must have a very large amount of data to sync or iCloud was experiencing some kind of bug or glitch. I'm assuming that the problem went away eventually? iCloud usually stops throttling after some period of time.

**Comment by tech-ki** [comment]
Yes the issue doesn't show up anymore now. I have a lot in my icloud but my data in zavalla isn't too much (yet). Thank you!
