### ISSUE TITLE
CloudKit Syncing Error when syncing with iCloud

### ISSUE THREAD

**Issue by milamavens** [vincode-io/Zavala#206]
Hi,

I am receiving an error message when attempting to sync my outlines with iCloud:

> CloudKit Syncing Error
> Request Rate Limited: transfers to and from the server are being rate limited at this time.

I haven't found a solution for this type of message by searching online. The alert appears several seconds after syncing with iCloud and persistently re-appears even after being dismissed.

**Zavala version:** 2.0.8
**OS:** macOS Sonoma 14.1.1

**Steps to reproduce:** Sync outlines via iCloud.

**Comment by vincode-io** [comment]
This is an error from Apple itself about iCloud syncing. It really shouldn't even appear, but will if they are limiting how fast we can sync without providing any data on how much to slow down.

Do you have a large number of total rows across all outlines by any chance? Was this on an initial sync or just a regular as you work sync?

**Comment by milamavens** [comment]
> Do you have a large number of total rows across all outlines by any chance? Was this on an initial sync or just a regular as you work sync?

I do have a large number of rows, yes. Majority of these rows are from a few large outlines. This was just a regular as-I'm-working sync.

Would you recommend reducing the size of these outlines for syncing to continue? If so, would splitting up my larger outlines into smaller ones solve the issue?

**Comment by vincode-io** [comment]
Splitting up the outlines wouldn't help any. Are you importing a large number of rows from another app? That may be why you are seeing it right now.

This error usually clears itself up fairly quickly. It is just telling you that Apple has temporarily slowed down syncing for you, but that it will speed up again.

**Comment by vincode-io** [comment]
Are you leaving Zavala up and running for a very long time? Do you still get this error after restarting Zavala?

**Comment by milamavens** [comment]
No, I'm not leaving Zavala running for a long time. I still receive this error after restarting Zavala, and I receive it each time I restart.

My apologies for the radio silence!

**Comment by vincode-io** [comment]
If you don't mind, could you download the [TestFlight version of Zavala](https://testflight.apple.com/join/iFbND23m) and let me know if you still are having this issue. The iCloud syncing was completely rewritten in this version and may have resolved your problem.

**Comment by milamavens** [comment]
I downloaded the new version on macOS and I didn't have issues with syncing over iCloud at all! The spinning indicator next to the iCloud header in the sidebar was a really nice touch, too.
