### ISSUE TITLE
In dark mode, text selection highlight is too dark

### ISSUE THREAD

**Issue by glebd** [vincode-io/Zavala#210]
First, let me say that Zavala is positively wonderful and so pleasant to use—I just switched from Omni Outliner. Thank you very much!

A minor nitpick: in dark mode sometimes the selection highlight is very dark and barely discernible. Could be related to hyperlinks (see the attached screenshots).

Non-link text is OK:

![Image 16-01-2024 at 18 04](https://github.com/vincode-io/Zavala/assets/32538/d3cdf492-25c5-4550-a5aa-f1051da07252)

Link selection is barely visible:

![Image 16-01-2024 at 18 02](https://github.com/vincode-io/Zavala/assets/32538/4c448f41-c9e2-40fb-87ee-32c99b283da6)

**Comment by vincode-io** [comment]
You are right. It is too hard to see. That green on black doesn’t work too well when it has had some transparency added to it. I’ve made it brighter so that we can see it better.

￼

Look for this change in the upcoming 2.3 release.

-Maurice

**Comment by glebd** [comment]
Excellent, thank you!
