### ISSUE TITLE
Localization update.

### ISSUE THREAD

**Issue by ccgus** [vincode-io/Zavala#214]
https://github.com/vincode-io/Zavala/blob/f36e920f1dfb85c63d4f3d23b80188876fb5d79e/Zavala/Resources/Localizable.strings#L148

I think this should say "The outline _will_ be deleted and unrecoverable." Same with the plural version.

**Comment by vincode-io** [comment]
Thanks Gus! I've looked at that message dozens of times and never noticed the missing word. Doh!
