### ISSUE TITLE
On iOS, the indent button (->|) moves the current item up instead of indenting it

### ISSUE THREAD

**Issue by glebd** [vincode-io/Zavala#215]
To reproduce on iOS (tried on iPhone 15 Pro Max, iOS 17.3):

1. Create a new outline item or tap an existing item.
2. Tap the indent button (->|).

**Expected result**: the item is indented.
**Actual result**: the item moves up.

**Comment by vincode-io** [comment]
Are you sure you aren't accidentally hitting the move up button? The buttons are a little tight on the iPhone and the move right icon looks heavier on the right hand side.

As an experiment, try using your opposite hand to tap the move right (indent) button.

**Comment by vincode-io** [comment]
Since where the hit area is rather confusing, I am going to change the icons to ones that better represent where you should tap. This will make it look like Move Up (Indent) button has moved away from the Move Up button.

**Comment by glebd** [comment]
Thank you, I may have accidentally hit the other button, but separating them a little bit more should help.
