### ISSUE TITLE
Crash on entry delete on iPad

### ISSUE THREAD

**Issue by SamSandq** [vincode-io/Zavala#218]
Swiping left to delete a line on iPad, latest Zavala, crashes the app

**Comment by vincode-io** [comment]
Does this happen on all outlines or just a specific one? It sounds like you might have a corrupted outline. Zavala should be prompting you to fix it when you open it. If this isn't happening, I recommend you export the outline as an OPML file and then reimport it.

Corrupt outlines shouldn't happen in the latest versions of Zavala and it will try to fix any outlines that may have gotten corrupted in previous versions.

**Comment by SamSandq** [comment]
Thanks for the prompt response!

Sorry to say, it’s several. One did say it’s corrupted on my Mac, and
repaired it, but the ipad version, although updated, still crashes.

I verified that several of my outlines exhibit the same problem.

Sam


lör 10 feb. 2024 kl. 21:33 skrev Maurice Parker ***@***.***>:

**Comment by vincode-io** [comment]
If you export the outline as an OPML file, delete the outline, and then import the OPML file is it fixed? If so the outline was corrupted.

**Comment by SamSandq** [comment]
I have tested it on several outlines, and it crashes on all. Note that I’m on 16.7.5  an old iPad.-----------------------------------------------Sam11 feb. 2024 kl. 01:28 skrev Maurice Parker ***@***.***>:﻿
If you export the outline as an OPML file, delete the outline, and then import the OPML file is it fixed? If so the outline was corrupted.

**Comment by vincode-io** [comment]
Thanks for letting me know that you were on iOS 16 still. I could reproduce the bug there and come up with a fix for it. Version 2.3.2 has been submitted to the App Store and should be available there in the next day or so.

Thanks for reporting this and working with me on the solution.

**Comment by SamSandq** [comment]
I am happy to report that the fix was already available on the Appstore, and it works perfectly.Great job, Maurice!-----------------------------------------------Sam11 feb. 2024 kl. 21:45 skrev Maurice Parker ***@***.***>:﻿
Thanks for letting me know that you were on iOS 16 still. I could reproduce the bug there and come up with a fix for it. Version 2.3.2 has been submitted to the App Store and should be available there in the next day or so.
Thanks for reporting this and working with me on the solution.
