### ISSUE TITLE
CloudKit Syncing Error - You can't save the same record twice

### ISSUE THREAD

**Issue by valleydali** [vincode-io/Zavala#219]
I get this error frequently when opening Zavala on my iPhone.

![image](https://github.com/vincode-io/Zavala/assets/37566098/6806cfcd-d7a4-4884-b6d5-bfdd9d8b9f43)

Zavala version: 2.3.2
iOS version: 17.3.1

I also use Zavala on my Mac, and syncing seems to work, so perhaps the error message is spurious?

Zavala version on Mac: 2.3.1
macOS version: 14.3.1

**Comment by vincode-io** [comment]
It looks like something on your iPhone got a little wonky. If you remove the iCloud account and add it again on your iPhone, does the issue go away? I know it isn't the best solution, but I've never seen this error before and have no way of debugging your personal device.

**Comment by vincode-io** [comment]
I mean "wonky" with your Zavala iCloud account on your iPhone. Nothing else.

There aren't any logs that would help. What I really need to see is the contents of your iCloud account folder which is very difficult to extract. That really isn't an option at this point.

Adding and removing your iCloud account is perfectly safe. It doesn't impact any application settings. It doesn't impact any Outline data stored in the cloud. The only thing you would lose is non-sync'd view metadata. That is things like if a row is Expanded or Collapsed or the Focus state.

**Comment by vincode-io** [comment]
Correct. Only use Zavala's settings to disable and enable the Zavala iCloud account.
