### ISSUE TITLE
Pressing Enter on an empty line

### ISSUE THREAD

**Issue by mjtys** [vincode-io/Zavala#233]
I'm loving the application! 

It would be great to have a feature where pressing enter on a blank line goes back an indentation (shift + tab). I have the muscle memory of pressing enter twice to go up a level to start on another nested list.

**Comment by vincode-io** [comment]
I haven't heard of this feature in an outliner before. Which one were you using that worked this way?

**Comment by vincode-io** [comment]
I see that behavior in Dynalist, but don't see any way to do it in Workflowy. Workflowy seems to work like Zavala and every other outliner I've used.

I don't think this is a normal outliner behavior and am not seeing much use in adding it. I realize you are used to how Dynalist handles enter on an empty line, but most people probably expect the standard behavior.

**Comment by mjtys** [comment]
Thank you once again for the response. Workflowy does have this functionality as I confirmed before writing the previous comment, I believe it is just active as standard. 

You would know outliners better than me, but I'm not sure in which situation you would keep pressing enter and having a list of blank bullets as other outliners have like you mentioned. The pressing of enter on a blank line to go up a level seems like a quality of life change so you can continue typing without moving both hands to go up a level e.g. finish a level 2 list press enter twice and you can start writing a level 1 heading.  

As a worst case, would it be possible to get this feature as a toggleable option in the settings in 3.0 or a future testflight build?

Thank you for the consideration and loving the app.

**Comment by vincode-io** [comment]
I see where my confusion came from with Workflowy. It only moves up a level if you hit enter on an empty line, _on the last indented entry_. Otherwise you get a blank line.

This makes me more inclined to implement this, but I'm still unsure about it. Let me think about it some more...

**Comment by mjtys** [comment]
That's correct, apologies for the confusion!

Whilst using Zavala today there are a couple more features I'm wondering if I can push for implementation as well. 

1. If you use the arrow keys to cycle left and right and then press enter/return, it would split the line and create a new bullet underneath with whatever is right of the typewriting indicator

2. Is it possible to implement the feature of sort the notes list via last updated rather than alphabetical?

Apologies for all of the feature requests, but thank you again for your consideration.

**Comment by vincode-io** [comment]
I've implemented your request to outdent the last child row when hitting Return. I also changed Zavala to split rows using Return when the cursor is in the middle of a Topic, as you suggested in Item 1 above. I was actually in the middle of implementing this change when you requested it.

Check out these changes in Zavala 2.5 by signing up for [TestFlight](https://testflight.apple.com/join/iFbND23m). (The latest Mac build might not be approved for testing yet, but should be soon.)

As for Item 2 above, I would like to have more powerful Outline management features, but those probably won't happen until I release Zavala 3.0.

**Comment by vincode-io** [comment]
Thanks for the bug report. I've got a fix in TestFlight if you want to check it out.

The TestFlight build notes are what has changed since the last production release, so they are per revision. I put them in an order that I feel shows what's more important first. I don't think everyone reads all the change notes, so more minor fixes end up around the bottom.

If you are looking for older change logs you can find them on the project [GitHub Releases](https://github.com/vincode-io/Zavala/releases).
