### ISSUE TITLE
Support editor overscroll

### ISSUE THREAD

**Issue by jordanbaird** [vincode-io/Zavala#235]
It would be great if Zavala's editor could scroll past the bottom of the outline. Currently, if the outline is really long, the bottom of the document stays at the bottom of the screen, which can make it harder to see what's being edited. Ideally, the bottom of the document would scroll to around the middle of the editor, or there could be multiple options on where to stop the scrolling, similar to Xcode.

**Comment by vincode-io** [comment]
@jordanbaird I just submitted a build of that contains your change to TestFlight. Look for version 2.5.3 there to validate that I made the change you were looking for.

**Comment by jordanbaird** [comment]
Thanks! Where can I get an invite code to TestFlight?

**Comment by vincode-io** [comment]
https://testflight.apple.com/join/iFbND23m

**Comment by jordanbaird** [comment]
Just got the TestFlight build. Works perfectly!
