### ISSUE TITLE
Row Deep Linking

### ISSUE THREAD

**Issue by vincode-io** [vincode-io/Zavala#237]
Add the ability to create links directly to Rows. `Copy Row Link` should be added to the Row context menu as well as the main menu. We should probably add a keyboard shortcut as well (shift-cmd-C).

This was requested in discussion #236.

**Comment by vincode-io** [comment]
This has been implemented and will be in the upcoming 2.6 release.

**Comment by aga5tya** [comment]
@vincode-io Thanks for adding this so quickly; I tested it on the latest build, and it works as expected.

**Comment by aga5tya** [comment]
Just a couple of observations
- On markdown export, it still points to the entire outline doc reference. I believe the suggestion [here](https://github.com/vincode-io/Zavala/discussions/236#discussioncomment-9553183) might make that work.
- It would be nice to have the backlinks surfaced at the end of the document for row-level linking too, similar to how it works for outlines.

**Comment by vincode-io** [comment]
@aga5tya The markdown export is definitely broken. See issue #181 for how I will fix it. I've been hesitant to make this change because it might break some peoples expectations (and Shortcuts) when it gets made.

My testing shows that backlinks are working for row level links. Are you suggesting that we have row-level backlinks? If so, what would the title be for the backlink? That's where I think things might be getting overly complicated.
