### ISSUE TITLE
Toggle-able outline chrome

### ISSUE THREAD

**Issue by jsismail** [vincode-io/Zavala#241]
Some outline chrome (see attached picture) should be toggle-able.  Indentation is enough to define the outline's structure.  Disclosure triangles are necessary outline chrome.  All other outline chrome can be visually noisy.  It would be nice if there were an option to turn off the dots and vertical lines.

![zavala_outline_chrome](https://github.com/vincode-io/Zavala/assets/3581864/f1865865-6e2b-4837-8340-24a5f742f16d)

**Comment by jsismail** [comment]
Just realized that I could created this issue from the discussion thread https://github.com/vincode-io/Zavala/discussions/239#discussion-6726778.  Linkg here for completeness.

**Comment by vincode-io** [comment]
If we suppressed the bullets, how do you tell the difference between a Row with multiple paragraphs in it and multiple Rows?

The vertical bars help show how indented a Row is. I find this useful and don't think it clutters up the UI.

I'm trying to keep Zavala as simple as possible. There needs to be a clear case for how this improves Zavala sufficiently to warrant the additional complexity.

**Comment by jsismail** [comment]
That's fair and I appreciate the design direction.  

Regarding telling the difference between a row with multiple paragraphs and multiple rows, it could be addressed by a different spacing height - smaller for multiple paragraphs between paragraphs, larger for multiple Rows between rows.

Regarding the vertical bars, the indentation itself imply the indentation.

I think the use cases we have are mind are different.  I'm thinking about "light" outilnes - usually single-line rows.  Visually, there can be more outline chrome than outline information.  Perhaps "heavy" outlines don't suffer from the same imbalance.

**Comment by vincode-io** [comment]
Design decisions like this are very subjective. I appreciate you bringing it up and expressing your thoughts.

For now though, I'm going to close out this issue. I'll reference or reopen this issue if we find out that the vertical bar or the bullets are causing an accessibility or a severe usability issue.
