### ISSUE TITLE
Cut-and-Paste simple text outlines from other apps

### ISSUE THREAD

**Issue by jsismail** [vincode-io/Zavala#242]
Implement the ability to import a simple text outline created in any external app (e.g. Notes, BBedit).  The external outline would have to be created using either tabs or cmd-] for indentation.  It would be helpful to go ther other way as well (e.g. from Zavala to Notes).  Cutting and pasting an outline, as opposed to an entire file, is what's relevant since external dosuments would genearlly have content that doesn't conform to an outline.

**Comment by vincode-io** [comment]
I'm pretty sure that this is a duplicate of #189. If you feel that #189 doesn't cover all your points, we can comment on it or reopen this issue.
