### ISSUE TITLE
Sorting Documents

### ISSUE THREAD

**Issue by jfmartin67** [vincode-io/Zavala#265]
Is it possible to add the capability to sort the documents list? By title? By last modified date? By creation date? Thanks for your consideration.

**Comment by vincode-io** [comment]
I'll consider it for a future release.

I'm thinking that this setting should be on a per Tag basis.

**Comment by jfmartin67** [comment]
Mmmm per tag or global.

**Comment by vincode-io** [comment]
This has been implemented and will be in the upcoming 3.1 release. Look for a build in TestFlight soon to validate the enhancement.

**Comment by jfmartin67** [comment]
Thanks, I will look into it! :-)
