### ISSUE TITLE
Return button bug: Details for replicating

### ISSUE THREAD

**Issue by colindavey** [vincode-io/Zavala#266]
This refers to this discussion item (264). 

Hi, I’m finding that the note button is putting the note on the wrong item. When the cursor is in an item, and I hit the note button, the note gets created under a different item. As far as I can tell, the note gets added to a different item which was recently edited.

**Comment by colindavey** [comment]
To replicate, _on an iPad_

1. Create new outline. Name it ‘test’.
2. Add one item and type ‘one’.
3. Hit return to create a new item and type ‘two’. The cursor is now at the end of the 2nd item.
4. Press the note button.

Notice that the new note is on the first item, though it should be on the second item. 

The specific things I typed no doubt don’t matter.

**Comment by colindavey** [comment]
I just tested this on a Mac book and found that it works fine there.

**Comment by vincode-io** [comment]
I'm not able to recreate this issue. What version of Zavala are you using and what is the model of iPad you have?

If you could share a video of the bug happening, it might help us better understand what is happening.

**Comment by colindavey** [comment]
Thanks for the reply! I’m using Zavala 3.04, on a 5th generation iPad Pro, with iOS 18.1. Attached is a video. 

By chance I got the ‘CloudKit Syncing Error” message that I’ve also been meaning to ask about. 

https://github.com/user-attachments/assets/eefcfc06-1ab7-4bfe-8259-a98eb6d649fc

**Comment by vincode-io** [comment]
I see the problem now. The button you are pressing is actually the return button. The Note button is the one right next to it. I'll get this bug fixed as soon as I can.

That iCloud error usually only occurs when the iCloud servers are unavailable. This could happen if your connection to the internet is fine, but for some reason Apple's servers couldn't be reached.

Are the Outlines correctly syncing back and forth to your Mac?

**Comment by colindavey** [comment]
So it’s for inserting a newline into a topic, (which can look like a note)? So just a different bug?

I did a quick test on a borrowed Mac. I’m getting a new Mac today so I’ll be able to test it more. For a newline on a Mac, is it something like ctrl-return?

**Comment by vincode-io** [comment]
In Zavala, Notes are a separate field. See Help for more details on how it is used.

The Newline keyboard shortcut is option-return. This is the more standard usage on Apple platforms.

**Comment by vincode-io** [comment]
This issue has been fixed and will be in the upcoming 3.0.5 release.

**Comment by colindavey** [comment]
Awesome thanks!

How can I email you? I saw in your blog that you like getting emails. I also saw something about using “feedback” but I couldn’t find a feedback button or link anywhere. I’ve been running my life with outline software for 35 years, the last 15 with circus ponies notebook.

**Comment by vincode-io** [comment]
There is a Feedback option in Settings on iOS. There is a menu item under Help on the Mac.
