### ISSUE TITLE
Unable to Navigate Out of Notes Level with Arrow Keys

### ISSUE THREAD

**Issue by Risinggoblin** [vincode-io/Zavala#269]
When a note is created for a row in Zavala Outliner, navigation using the arrow keys becomes restricted to the notes level. Users are unable to move up or down to escape the notes level, effectively getting “stuck” in the notes section.

### Steps to Reproduce

1. Open Zavala Outliner.
2. Create a new row and add a note to it.
3. Attempt to navigate away from the notes level using the up or down arrow keys in the keyboard

### Environment

- App Version: 3.06 (from Mac App Store)
- Device: Macbook Air 2020
- Operating System: macOS Sequoia 15.2

**Comment by vincode-io** [comment]
Since it is somewhat difficult to get into the Notes field, I don't want to exit the Notes field on up and down arrow keys. I could see people exiting the Notes field unintentionally which would be frustrating.

To exit the Notes field use the ESC key instead.

**Comment by Risinggoblin** [comment]
Understood. Esc key method is good enough.
