### ISSUE TITLE
Should be able to drag a row to the Title line

### ISSUE THREAD

**Issue by vincode-io** [vincode-io/Zavala#33]
This is a request from @brentsimmons that was originally part of #32.

**Comment by vincode-io** [comment]
I don't think I can implement this and still keep compatibility with OPML files. OPML treats the Title as a special field in the header that doesn't have the same attributes as Rows do.

I still don't know what I would do with any child Rows that got dragged to the title line. Maybe I've painted myself into a corner with the current design, but I just can't figure out how I can make this work.

**Comment by vincode-io** [comment]
@brentsimmons I think about this request all the time. What really got me hung up was what to do with other rows in the outline when one of them was promoted above them. I think I might implement a new feature that is very similar to what you are describing here that doesn't have that dilemma.

It is called "Extract". You could select a row and it would be used as a basis for a new outline. It would be removed from the current outline with all its descendants to create the new outline. In its place would be a link to the newly created outline.

Is that close to what you were after or am I still out in left field?

**Comment by brentsimmons** [comment]
On reflection, I realize my idea wasn’t very good :)

Extract sounds like a good feature.
