### ISSUE TITLE
New Outline function should always be available

### ISSUE THREAD

**Issue by vincode-io** [vincode-io/Zavala#36]
Should put the Outline in the current folder.  If unavailable due to being in a smart folder, the last folder added to should be used, otherwise the default "Outlines" folder should be used.

**Comment by vincode-io** [comment]
After thinking through this, we will have to just try to guide the user on how to use the app as much as possible.

**Comment by gruber** [comment]
If you switch from folders to tags the problem goes away. New Outline always makes a new outline with tags that meet the current sidebar item’s criteria. (*Ducks.*)

I also don’t think either of the current smart folders is necessary or useful. Why have “Recents” if outlines are sorted by (or even just can be sorted by) modification date? Recents should just be the top of a sorted list of all outlines.

Favorites, as a sidebar grouping, is going against Apple’s trend of “pinning”, like pinned notes in Apple Notes and pinned chats in Messages, which just keeps those things at the top of the list.

**Comment by vincode-io** [comment]
I agree that the current Library options aren't very good. I'm trying to work through how tags would work and I'm not able to visualize it yet.

Where does the tag name come from?  How are they created and where in the UI is the tag assigned to the Outline?

What happens if nothing is selected in the sidebar and you want to create an Outline?

**Comment by vincode-io** [comment]
@gruber I downloaded Vesper to see how tagging was done in it and I see your point of view much better. I see an obstacle to adopting it and wondered if you had any solutions.

The Vesper sidebar was a custom component where either the All Notes or a tag was selected.  The Apple sidebar may have a state where it is not selected. The main one is when an iPhone launches and the sidebar is really the first scene shown.

This wouldn't be a problem if we only had one account like Vesper. But with iCloud you need to keep the local account separate from the iCloud one. Switching a single account back and forth just doesn't work well.

So if nothing is selected, which account does an outline go in? And how does the user move an Outline they created in their local account to the iCloud one, should they enable it?

**Comment by vincode-io** [comment]
I ended up resolving this by removing folders which will be replaced with tags for organizing.  As for selecting the correct account, we select the last selected account if there is one or else we select the first account.

**Comment by gruber** [comment]
I’m not trying to be glib, but I would just get rid of “accounts”. You’d either have iCloud sync on or off. Off and everything is device local, on and everything just syncs. That way you never worry about “where”.

**Comment by vincode-io** [comment]
I agree, but it gets real nasty if you have to merge a local account with iCloud.

1) Create an iCloud Account on Device A and add outlines
2) Create a Local Account on Device B and add outlines
3) Enable iCloud on Device B

Now you are not only pulling from iCloud when enabling sync, but also pushing.  You are having to deal with conflicts and duplicates.  I'm not sure I could make it a good experience.
