### ISSUE TITLE
Custom Attributes / Column Support

### ISSUE THREAD

**Issue by vincode-io** [vincode-io/Zavala#39]
This enables the user to create custom fields that are associated with a row.  These fields can be used for sorting or tracking additional metadata.

<img width="1033" alt="Screen Shot 2020-12-13 at 10 57 36 PM" src="https://user-images.githubusercontent.com/16448027/102042257-01885500-3d97-11eb-869f-21ec6b0be246.png">

**Comment by MahatmaFatalError** [comment]
@vincode-io What exactly was the rationale for the decision? Can't find the manifesto you mentioned. IMHO the "Column Feature" is the most important missing feature.

**Comment by vincode-io** [comment]
This isn't completely dead. It has been superseded by #134. It won't be implemented as columns though. Horizontal scrolling isn't very user friendly and because Zavala is also an iPhone and iPad app, this is especially true. Nothing is finalized, but read the blog post in #134 to better understand the direction I think we will eventually go.
