### ISSUE TITLE
AppleScript Support

### ISSUE THREAD

**Issue by vincode-io** [vincode-io/Zavala#42]

**Comment by olofhellman** [comment]
Hoping to get a feel for the scope of what would be the basics for a Scripting Interface.  

app 
    contains outlines (outline) (create, delete, count)
outline  
    has title  (get, set)
    contains rows (row) (create, delete, count)
    contains tags (create, delete, count)
row
    has title (text) (get, set)
    has note (text) (get, set)
    has collapsed (boolean) (get, set)
    contains rows (row) (create, delete, count)

Hey!  That looks like an outline!
Are these the right terms for the obljects?
What else might be part of the basics?  indent or outdent a row?  indentation level of a row? save outline as <format> ?

**Comment by vincode-io** [comment]
Hey Olof! Glad to see you are interested.

Instead of Title, I use Topic to denote the main text for a Row.

You should be able to indent and outdent a row.

We don't have a Save As command, but we do have Import and Export commands that would be useful to be scripted.

**Comment by vincode-io** [comment]
We also will want a way to get the URL of the currently shown Outline in the key window. That way we can support [Hook](https://hookproductivity.com/).

**Comment by vincode-io** [comment]
Since we've implemented full Shortcuts support in Zavala 2.0 and AppleScript has Shortcuts interop, I think the intent of this issue has been resolved. True AppleScript support would be nice, but I don't think it needs to be a project goal anymore.
