### ISSUE TITLE
Focus Command

### ISSUE THREAD

**Issue by vincode-io** [vincode-io/Zavala#48]
### Zoom in on a specific Headline's hierarchy as if it is the whole outline.  

* Should be undoable and provide some visual feedback that the row is focused and a way to go back to the full headline. An eye icon should be used in the Mac Toolbar and the iOS Navbar.
* All Outline level functions should work on a Focused Row as if it is an Outline.

**Comment by pramjan** [comment]
Hi Maurice,

This is an exciting feature - is there any update on this?
Thank you for your app once again, really helpful!

**Comment by vincode-io** [comment]
It is still planned, but probably won't make it in the next release (which is taking way too long already).
