### ISSUE TITLE
CloudKit warnings

### ISSUE THREAD

**Issue by MadaboutDana** [vincode-io/Zavala#74]
I’ve been experimenting with OPML imports, and I regularly receive the message “CloudKit Syncing Error – Partial Failure: some items failed, but the operation succeeded overall” in multiple situations:

(a) immediately after importing the OPML file
(b) when I move to the new (imported) outline 
(c) regularly while I’m working on the new (imported) outline

The problem appears to vanish when I exit Zavala and then reopen it, but after exiting, I’m asked to submit a Crash error report (even though Zavala appears to have exited neatly).

**Comment by MadaboutDana** [comment]
Ah, no, I lied. I’m still receiving CloudKit Syncing Error alerts for one specific outline, which is quite a big one.

**Comment by vincode-io** [comment]
If you are comfortable with sharing your Outline, would please send it to mo@vincode.io? I need some way to recreate your problem and there is probably something unique about your Outline that I haven't taken into consideration.

**Comment by MadaboutDana** [comment]
body{font-family:Helvetica,Arial;font-size:14px}Ah, great stuff!  Bill MASLENLe Bois de la Garde | 1519 chemin du Bois de la Garde | FR–71250 BuffièresT +33 3 85 59 65 25 | M +33 6 51 94 99 ***@***.*** On 30 March 2021 at 18:33:59, Maurice Parker ***@***.***) wrote: 
Turns out we had a problem processing a large number of changes via iCloud. If we change too much at a time, iCloud will ask us to break it up. We were sending the outline data in the wrong order when that happens.
This is fixed and will be in the next update. (coming in a day or two)
