### ISSUE TITLE
Preserve strikeout in Markdown output?

### ISSUE THREAD

**Issue by TheMartianObserver** [vincode-io/Zavala#75]
Currently, a completed item in an outline shows with a strikeout in this app, which is great! When exporting to Markdown, however, that indicator is lost. Might be nice to preserve that in the output?

Basic Markdown does not unfortunately support strikeouts, but many processors (like Github's processor) support using two tildes like `~~thing to strikeout~~` = ~~thing to strikeout~~. Another option might be to use HTML and wrap the completed item in a `<del></del>` tag, which seems to work across implementations as well.

**Comment by vincode-io** [comment]
I used the `~~` syntax to denote completed items in outlines exported as markdown. This change will be in the upcoming Alpha 2 release.
