### ISSUE TITLE
observations during update to alpha 2

### ISSUE THREAD

**Issue by Thomas-U** [vincode-io/Zavala#83]
I guess it is not really an issue but this is my observation:

After reading your blogpost I started [Check for Updates...]. The info window came up, I started the update.

Little Snitch alerted to permit the connection to GitHub. I allowed it and in the next dialog, the progress bar started to move back and forth – forever.

I quit Z and opened it again, clicked CfU..., info about the update, started, LS wanted another permission for a different GH address. After that again the endless moving progress bar...

I quit and restarted everything once more. This time the update went fast and well.

I suspect that the updater gets irritated when it can not start the update immediately (timeout?). As I gave Zavala forever LS permission for both URLs all went well at the 3rd attempt.

**Comment by vincode-io** [comment]
Thanks for the detailed writeup. The update package I am using, Sparkle, is the experimental version and may have some bugs in it. In fact, it is amazing that it works as well as it does! I'm sure that your are seeing a bug where it doesn't report that it couldn't connect.

I plan using the Mac App store exclusively for distributing the Mac app, so hopefully updates go more smoothly for us in the released version.
