### ISSUE TITLE
Inserting text into a new outline

### ISSUE THREAD

**Issue by jbrayton** [vincode-io/Zavala#84]
On macOS after initially creating a new outline, I am finding it difficult to make the text view (?) in the body of the outline be the view that accepts keyboard input.

I find that the mouse cursor only becomes the I-beam cursor when I mouse over the very first line under the “Tags” button. Even then, clicking it does not seem to result in the text view/field accepting text input. I click and nothing happens, then when I type get a sound that seems to indicate macOS not knowing what to do with my keystrokes.

I hope that's clear. If not I am happy to try to clarify.

Version 1.0.0 (23) running on Big Sur.

**Comment by vincode-io** [comment]
There is no row created yet. I designed it from the perspective of using the keyboard. The return key takes you from the title to the tags. Then from the tags where it creates your first row and you can begin editing.  I can see now that this might be confusing and needs some work.

I'm not set on how to make this better yet, but I'll probably do something like creating a row if the user tries to click on the empty outline area.

**Comment by jbrayton** [comment]
Oh! Return works for me as you describe. Thanks.

**Comment by vincode-io** [comment]
This is now more intuitive and adds a row if you don't have one when you tap in the blank area of the Outline Editor. Look for it in the next release.

**Comment by jbrayton** [comment]
Nice – thanks!
