### ISSUE TITLE
Feature Request: Create new Outline when Link does not exist during edit

### ISSUE THREAD

**Issue by navigator8** [vincode-io/Zavala#92]
Create new Outline when Link does not exist during edit. Like in wiki. [[]] will create a link that does not exist yet.

This will cut the number of steps.

**Comment by vincode-io** [comment]
I really want to avoid Wiki syntax. I think it makes the documents look ugly.

What do you think about a "New Outline" button on the Link dialog box that creates a new Outline if the URL field is empty and creates a link to it? The new Outline would have a title that is the same as the linked text. That should streamline the workflow for creating new documents.

**Comment by navigator8** [comment]
Hi Maurice,

I am sorry I was not clear enough.  One of my attractions to Zavala is the neat presentation. Yes, wiki notation will erode this. I agree.

Below is perfect.
>>>

What do you think about a "New Outline" button on the Link dialog box that creates a new Outline if the URL field is empty and creates a link to it? The new Outline would have a title that is the same as the linked text.

>>>

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vincode-io** [comment]
I've added this to the upcoming 1.1 release.
