### ISSUE TITLE
Pre-release Download Link not working - Not Found

### ISSUE THREAD

**Issue by flotpg** [vincode-io/Zavala#97]
Hey Team.
The download link is not working:
https://github.com/vincode-io/Zavala/releases/download/1.0.1/Zavala.app.zip
![CleanShot 2021-06-28 at 13 13 13](https://user-images.githubusercontent.com/20798074/123627705-9bcf5800-d812-11eb-80bf-311bf08b2621.png)
Best regards, Flo.

**Comment by vincode-io** [comment]
Thanks! I've updated the README to point people to the App Store now that Zavala 1.0 is out.

**Comment by flotpg** [comment]
@vincode-io thx!
