### ISSUE TITLE
[macOS] Showing the sidebar when the window has a minimal size renders the app unresponsive.

### ISSUE THREAD

**Issue by lutzmi** [vincode-io/Zavala#98]
Steps to reproduce:

- Hide the sidebar.
- Make the window a small as possible.
- Hit the "toggle sidebar" button in the toolbar.

=> The app will not react to any user input (even the menus will not show up) until the app is quit and restarted.

Add.: Just saw that the same thing happens, if an outline is visible (one is selected in the second column of the sidebar) and the window gets resized to it's smallest size.

Cheers, Michael

**Comment by vincode-io** [comment]
Thanks for the bug report. I've addressed this in the upcoming Zavala 1.1 release.

**Comment by lutzmi** [comment]
Great! Many thanks!

Kind regards,
  Michael
