### ISSUE TITLE
irritating alert after MAS update to Version 1.0.1 (26)

### ISSUE THREAD

**Issue by Thomas-U** [vincode-io/Zavala#99]
As Z was open, MAS quit it and installed the update.

It reopened after that and the alert appeared (screenshot).

After manually opening, Z works normally.

![Screen-Shot 2021-06-28 at 22 35 13](https://user-images.githubusercontent.com/171936/123701217-dad8ca00-d861-11eb-92d2-f79d9576db94.png)

**Comment by Thomas-U** [comment]
I forgot: macOS 11.4 (20F71) · MacMini (M1, 2020)

maybe M1 was to fast in reopening... ;-)

**Comment by vincode-io** [comment]
I just tested this on my wife's MBP and didn't have any problems. I think it must have just been a onetime fluke.
